# ATTACKCASE4: TEST WHETHER WRITEAT VALUE STORES AFTER CLOSING THE FILE

# Create a file
if "testfile.txt" in listfiles():
    removefile("testfile.txt")

myfile = openfile("testfile.txt", True)

# Initial write to the file
myfile.writeat("12345678", 0)

myfile.close()

myfile = openfile("testfile.txt", True)


try:
    assert "12345678" == myfile.readat(None, 0)

# It raised an Exception (as it was supposed to):
except Exception:

    log("Attackcase4 SUCCESS : CLOSE OPERATION NOT WORKING \n")

except RepyArgumentError:

    log("Attackcase4 SUCCESS : CLOSE OPERATION NOT WORKING \n")
    pass

finally:
    # Close the file after our attempt.
    myfile.close()
    pass

