


### Test 7: Testing undo

# clean up if the file exists.
if "testfile.txt" in listfiles():
  removefile("testfile.txt")


try:
  # create a file
    myfile=openfile("testfile.txt",True)
    myfile.undo();
    myfile.writeat("abc", 0)
    myfile.writeat("abc", 3)
    myfile.undo()
    myfile.undo()
    output = myfile.readat(None, 0)
    if(output != "abc"):
        raise Exception("Double undo incorrect")

except Exception as e:
    log("Undo Functionality broken!: ")
    log(e);
    log("\n")

