"""
This security layer inadequately handles the undo functionality

Note:
    This security layer uses encasementlib.r2py, restrictions.default, repy.py and Python
    Also you need to give it an application to run.
    python repy.py restrictions.default encasementlib.r2py [security_layer].r2py [attack_program].r2py 
    
"""
TYPE = "type"
ARGS = "args"
RETURN = "return"
EXCP = "exceptions"
TARGET = "target"
FUNC = "func"
OBJC = "objc"


class LPFile():
    def __init__(self, filename, create):
        # globals
        mycontext['debug'] = False
        self.LPfile = openfile(filename, create)
        self.size = 0
        self.pending_data = None
        self.pending_offset = None
        self.lock = createlock()

    def readat(self, bytes, offset):
        self.lock.acquire(True)
        if (bytes != None and bytes < 0) or offset < 0:
            self.lock.release()
            return self.LPfile.readat(-1, -1) #raises error
        if offset <= self.size and (bytes is None or offset + bytes <= self.size):
            result = self.LPfile.readat(bytes, offset)
            self.lock.release()
            return result
        else:
            try:
                result = self.LPfile.readat(bytes, offset)
            except Exception as e:
                raise e
            finally:
                self.lock.release()
        return result

    def writeat(self, data, offset):
        self.lock.acquire(True)

        if self.pending_data and self.pending_offset is not None:
            pending = self.pending_offset + len(self.pending_data)
        else:
            pending = 0

        if offset > max(self.size, pending):
            try:
                self.LPfile.writeat(data, offset)
            except Exception as e:
                raise e
            finally:
                self.lock.release()

        elif offset < 0:
            try:
                self.LPfile.writeat(data, offset)
            except Exception as e:
                raise e
            finally:
                self.lock.release()

        try: #I don't think there will be exceptions but using try finally just in case

            if self.pending_data:
                self.LPfile.writeat(self.pending_data, self.pending_offset)
                
                # Adjust the file size after a successful write
                if self.pending_offset + len(self.pending_data) > self.size:
                    self.size = self.pending_offset + len(self.pending_data)

            self.pending_data = data
            self.pending_offset = offset
        finally:
            self.lock.release()

    def undo(self):
        self.lock.acquire(True)
        self.pending_data = None
        self.pending_offset = None
        self.lock.release()


    def close(self):
        self.writeat("0", 0)
        self.pending_data = None
        self.pending_offset = None
        self.LPfile.close()

def LPopenfile(filename, create):
    file = LPFile(filename, create)
    file.size = len(file.LPfile.readat(None, 0))
    return file

# The code here sets up type checking and variable hiding for you.
# You should not need to change anything below here.
sec_file_def = {
    "obj-type": LPFile,
    "name": "LPFile",
    "writeat": {"type": "func", "args": (str, (int, long)), "exceptions": Exception, "return": (int, type(None)), "target": LPFile.writeat},
    "readat": {"type": "func", "args": ((int, long, type(None)), (int, long)), "exceptions": Exception, "return": str, "target": LPFile.readat},
    "undo": {"type": "func", "args": None, "exceptions": None, "return": type(None), "target": LPFile.undo},
    "close": {"type": "func", "args": None, "exceptions": Exception, "return": (bool, type(None)), "target": LPFile.close}
}

CHILD_CONTEXT_DEF["openfile"] = {
    TYPE: OBJC,
    ARGS: (str, bool),
    EXCP: Exception,
    RETURN: sec_file_def,
    TARGET: LPopenfile
}

# Execute the user code
secure_dispatch_module()