# Attack Case 5: RepyArgumentError and FileClosedError in writeat()

# The Repy API states that if multiple exceptions 
# are raised the one written first in the docstring 
# is raised

# writeat() should raise a RepyArgumentError if a
# RepyArgumentError and FileClosedError are raised

# clean up if the file exists.
if "testfile.txt" in listfiles():
  removefile("testfile.txt")

# create a file
myfile=openfile("testfile.txt", True)

# intial write to the file
myfile.writeat("12345678", 0)

# attempt to overwrite the beginning of the file
myfile.close()

# try invalid write to closed file
# should ONLY throw RepyArgumentError error
try:
    myfile.writeat("12345678", -1)
except RepyArgumentError:
   pass
else:
   log("FAILED ssm10021_attackcase5.r2py\n")
