# open file write data, close file
myfile = openfile("testfile.txt",True)
myfile.writeat('valid', 0)
myfile.writeat('invalid', 0)
myfile.close()

# open file , write data, close file
myfile = openfile("testfile.txt",True)
myfile.writeat('valid', 0)
myfile.close()

# reopen file
myfile = openfile("testfile.txt",True)
try:
    # Since file was closed while data was invalid, 
    # the backup data that was valid will be used
    assert('valid' == myfile.readat(None,0))
    # Close the file:
    myfile.close()
except:
    myfile.close()
    log("not handled properly")