# Attack Case 10: write and write again
# Try to write using a function
# for referencemonitor in reference_monitor_j*; do echo $referencemonitor under test; for testcase in jl14678_attackcase10*; do python repy.py restrictions.default encasementlib.r2py $referencemonitor $testcase; done; done

# clean up if the file exists.
filename ="attack10.txt"
if filename in listfiles():
    removefile(filename)

def write_again_attack():
    try:
        f = openfile(filename, True)
        
        def write_again(data):
            f.writeat(data, 5)
            
        f.writeat(write_again("writewritewrite"), 0)
        
        content = f.readat(50, 0)
        
        if "writewritewrite" in content:
            log("[!]Attack Case 10 successful\n")
        else:
            log("[*]Attack Case 10 failed\n")
        f.close()

    except Exception as e:
        log("Unexpected error during the attack: " + str(e) + '\n')
        return

write_again_attack()