#to check if undo works after closing file
if "testfile.txt" in listfiles():
  removefile("testfile.txt")
myfile=openfile("testfile.txt",True)
myfile.writeat("Hello there",0)
myfile.close()
try:
    myfile.undo()
except:
    pass
    #log("SUCCESSFUL DEFENSE")
else:
    log("ACCURACY_BUG: Undo performed for closed file\n")   